# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'podtest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

   pod 'LzyPodTest', :git => "https://github.com/GItHubNanmu77/LzyPodTest.git",:tag =>'2.0.0'
   pod 'Masonry'
  # Pods for podtest

  target 'podtestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'podtestUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
